name: Send Dinner Notification

on:
  schedule:
    - cron: "00 11 * * *" # 11:00 AM UTC
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/send-notification.yml

jobs:
  daily-update:
    name: Send Dinner Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Send notification
        run: |-
          python python/send-notification.py
        env:
          SEND_DINNER_WEBHOOK_URL: ${{ secrets.SEND_DINNER_WEBHOOK_URL }}
